name: GitHub Pages

on:
  push:
    branches:
      - pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        
      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: yarn build
        run: yarn build
        
      - name: rm -rf public
        run: rm -rf public
        
      - name: mv dist public
        run: mv dist public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
